# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'lymediabrower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lymediabrower
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'LYAutoUtils'
  pod 'MJRefresh'
  pod 'JXPhotoBrowser'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'AppCenter'

end
