# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'lymediabrower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lymediabrower
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'LYAutoUtils'
  pod 'MJRefresh'
  pod 'JXPhotoBrowser'
  pod 'RxSwift'
  pod 'RxCocoa'
  
end
